library(ggplot2) 
View(state.x77)
#sta=as.data.frame(state.x77[,c('Murder','Population','Illiteracy','Income','Forst')])
sta =as.data.frame(state.x77[,c('Murder','Population','Illiteracy','Income','Frost')]) 
 cor(sta)
 library(car)
 scatterplotMatrix(sta,spread=FALSE)
 fit=lm(Murder~Population+Illiteracy+Income+Frost,data=sta)
 summary(fit)
 library(leaps)
 leaps=regsubsets(Murder~Population+Illiteracy+Income+Frost,data=sta,nbest=4)
 plot(leaps,scale='adjr2')
 zstates=as.data.frame(scale(sta))
 zfit=lm(Murder~Population+Illiteracy+Income+Frost,data=zstates)
 coef(zfit)
 confint(fit)
   qqPlot(fit,labels = row.names(sta),id.method = 'identify',simulate = T)